pdf(file="Coverage00.bed.pdf",width=10,height=4)
aa=read.table("Coverage00.bed.origin")
bb=read.table("Coverage00.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage01.bed.pdf",width=10,height=4)
aa=read.table("Coverage01.bed.origin")
bb=read.table("Coverage01.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage02.bed.pdf",width=10,height=4)
aa=read.table("Coverage02.bed.origin")
bb=read.table("Coverage02.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage03.bed.pdf",width=10,height=4)
aa=read.table("Coverage03.bed.origin")
bb=read.table("Coverage03.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage04.bed.pdf",width=10,height=4)
aa=read.table("Coverage04.bed.origin")
bb=read.table("Coverage04.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage05.bed.pdf",width=10,height=4)
aa=read.table("Coverage05.bed.origin")
bb=read.table("Coverage05.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage06.bed.pdf",width=10,height=4)
aa=read.table("Coverage06.bed.origin")
bb=read.table("Coverage06.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage07.bed.pdf",width=10,height=4)
aa=read.table("Coverage07.bed.origin")
bb=read.table("Coverage07.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage08.bed.pdf",width=10,height=4)
aa=read.table("Coverage08.bed.origin")
bb=read.table("Coverage08.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage09.bed.pdf",width=10,height=4)
aa=read.table("Coverage09.bed.origin")
bb=read.table("Coverage09.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage10.bed.pdf",width=10,height=4)
aa=read.table("Coverage10.bed.origin")
bb=read.table("Coverage10.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage11.bed.pdf",width=10,height=4)
aa=read.table("Coverage11.bed.origin")
bb=read.table("Coverage11.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Coverage12.bed.pdf",width=10,height=4)
aa=read.table("Coverage12.bed.origin")
bb=read.table("Coverage12.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap00.bed.pdf",width=10,height=4)
aa=read.table("Gap00.bed.origin")
bb=read.table("Gap00.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap01.bed.pdf",width=10,height=4)
aa=read.table("Gap01.bed.origin")
bb=read.table("Gap01.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap02.bed.pdf",width=10,height=4)
aa=read.table("Gap02.bed.origin")
bb=read.table("Gap02.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap03.bed.pdf",width=10,height=4)
aa=read.table("Gap03.bed.origin")
bb=read.table("Gap03.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap04.bed.pdf",width=10,height=4)
aa=read.table("Gap04.bed.origin")
bb=read.table("Gap04.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap05.bed.pdf",width=10,height=4)
aa=read.table("Gap05.bed.origin")
bb=read.table("Gap05.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap06.bed.pdf",width=10,height=4)
aa=read.table("Gap06.bed.origin")
bb=read.table("Gap06.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap07.bed.pdf",width=10,height=4)
aa=read.table("Gap07.bed.origin")
bb=read.table("Gap07.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap08.bed.pdf",width=10,height=4)
aa=read.table("Gap08.bed.origin")
bb=read.table("Gap08.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Gap09.bed.pdf",width=10,height=4)
aa=read.table("Gap09.bed.origin")
bb=read.table("Gap09.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Inversion00.bed.pdf",width=10,height=4)
aa=read.table("Inversion00.bed.origin")
bb=read.table("Inversion00.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="Inversion01.bed.pdf",width=10,height=4)
aa=read.table("Inversion01.bed.origin")
bb=read.table("Inversion01.bed.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()