pdf(file="chr1.pdf",width=10,height=4)
aa=read.table("Depth.chr1.origin")
bb=read.table("Depth.chr1.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="chr2.pdf",width=10,height=4)
aa=read.table("Depth.chr2.origin")
bb=read.table("Depth.chr2.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="chr3.pdf",width=10,height=4)
aa=read.table("Depth.chr3.origin")
bb=read.table("Depth.chr3.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="chr4.pdf",width=10,height=4)
aa=read.table("Depth.chr4.origin")
bb=read.table("Depth.chr4.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="chr5.pdf",width=10,height=4)
aa=read.table("Depth.chr5.origin")
bb=read.table("Depth.chr5.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="chr6.pdf",width=10,height=4)
aa=read.table("Depth.chr6.origin")
bb=read.table("Depth.chr6.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="chr7.pdf",width=10,height=4)
aa=read.table("Depth.chr7.origin")
bb=read.table("Depth.chr7.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="chr8.pdf",width=10,height=4)
aa=read.table("Depth.chr8.origin")
bb=read.table("Depth.chr8.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="chr9.pdf",width=10,height=4)
aa=read.table("Depth.chr9.origin")
bb=read.table("Depth.chr9.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="chr10.pdf",width=10,height=4)
aa=read.table("Depth.chr10.origin")
bb=read.table("Depth.chr10.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()
