pdf(file="x00.pdf",width=10,height=4)
aa=read.table("Depth.x00.origin")
bb=read.table("Depth.x00.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x01.pdf",width=10,height=4)
aa=read.table("Depth.x01.origin")
bb=read.table("Depth.x01.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x02.pdf",width=10,height=4)
aa=read.table("Depth.x02.origin")
bb=read.table("Depth.x02.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x03.pdf",width=10,height=4)
aa=read.table("Depth.x03.origin")
bb=read.table("Depth.x03.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x04.pdf",width=10,height=4)
aa=read.table("Depth.x04.origin")
bb=read.table("Depth.x04.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x05.pdf",width=10,height=4)
aa=read.table("Depth.x05.origin")
bb=read.table("Depth.x05.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x06.pdf",width=10,height=4)
aa=read.table("Depth.x06.origin")
bb=read.table("Depth.x06.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x07.pdf",width=10,height=4)
aa=read.table("Depth.x07.origin")
bb=read.table("Depth.x07.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x08.pdf",width=10,height=4)
aa=read.table("Depth.x08.origin")
bb=read.table("Depth.x08.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x09.pdf",width=10,height=4)
aa=read.table("Depth.x09.origin")
bb=read.table("Depth.x09.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x10.pdf",width=10,height=4)
aa=read.table("Depth.x10.origin")
bb=read.table("Depth.x10.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x11.pdf",width=10,height=4)
aa=read.table("Depth.x11.origin")
bb=read.table("Depth.x11.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x12.pdf",width=10,height=4)
aa=read.table("Depth.x12.origin")
bb=read.table("Depth.x12.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x13.pdf",width=10,height=4)
aa=read.table("Depth.x13.origin")
bb=read.table("Depth.x13.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x14.pdf",width=10,height=4)
aa=read.table("Depth.x14.origin")
bb=read.table("Depth.x14.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x15.pdf",width=10,height=4)
aa=read.table("Depth.x15.origin")
bb=read.table("Depth.x15.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x16.pdf",width=10,height=4)
aa=read.table("Depth.x16.origin")
bb=read.table("Depth.x16.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x17.pdf",width=10,height=4)
aa=read.table("Depth.x17.origin")
bb=read.table("Depth.x17.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x18.pdf",width=10,height=4)
aa=read.table("Depth.x18.origin")
bb=read.table("Depth.x18.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

pdf(file="x19.pdf",width=10,height=4)
aa=read.table("Depth.x19.origin")
bb=read.table("Depth.x19.filter")
plot(aa[,2],aa[,4],type="l",ylim=c(0,300),col="red",main="read depth")
lines(bb[,2],bb[,4],type="l",ylim=c(0,300),col="green")
dev.off()

