#!/bin/bash

perl changeContigNamePaf.pl /public1/home/sc30797/wangzijian/update_Mo17/Step1_Gap_filling/03_hifiasm_contigs_to_replace/ontContig_hifiasmContig_forward.paf Mo17_ont_origin_asm.fahifiasmContig_forward.paf
perl changeContigNameHl.pl /public1/home/sc30797/wangzijian/update_Mo17/Step1_Gap_filling/03_hifiasm_contigs_to_replace/highlight.txt highlight.txt