pdf(file="x00.pdf",width=10,height=4)
aa=read.table("Depth.x00.origin")
bb=read.table("Depth.x00.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x01.pdf",width=10,height=4)
aa=read.table("Depth.x01.origin")
bb=read.table("Depth.x01.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x02.pdf",width=10,height=4)
aa=read.table("Depth.x02.origin")
bb=read.table("Depth.x02.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x03.pdf",width=10,height=4)
aa=read.table("Depth.x03.origin")
bb=read.table("Depth.x03.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x04.pdf",width=10,height=4)
aa=read.table("Depth.x04.origin")
bb=read.table("Depth.x04.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x05.pdf",width=10,height=4)
aa=read.table("Depth.x05.origin")
bb=read.table("Depth.x05.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x06.pdf",width=10,height=4)
aa=read.table("Depth.x06.origin")
bb=read.table("Depth.x06.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x07.pdf",width=10,height=4)
aa=read.table("Depth.x07.origin")
bb=read.table("Depth.x07.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x08.pdf",width=10,height=4)
aa=read.table("Depth.x08.origin")
bb=read.table("Depth.x08.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x09.pdf",width=10,height=4)
aa=read.table("Depth.x09.origin")
bb=read.table("Depth.x09.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x10.pdf",width=10,height=4)
aa=read.table("Depth.x10.origin")
bb=read.table("Depth.x10.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x11.pdf",width=10,height=4)
aa=read.table("Depth.x11.origin")
bb=read.table("Depth.x11.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

pdf(file="x12.pdf",width=10,height=4)
aa=read.table("Depth.x12.origin")
bb=read.table("Depth.x12.filter")
plot(aa[,2],aa[,4],type="l",col="red",main="read depth",ylim=c(0,300))
lines(bb[,2],bb[,4],type="l",col="green",ylim=c(0,300))
dev.off()

